"""groceryList change

Revision ID: 7b7bd563afb2
Revises: 86c12339e5bc
Create Date: 2024-04-07 10:06:30.245484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7bd563afb2'
down_revision: Union[str, None] = '86c12339e5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_list_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('grocery_list', sa.Column('icon_idx', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grocery_list', 'item_icon', ['icon_idx'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grocery_list', type_='foreignkey')
    op.drop_column('grocery_list', 'icon_idx')
    op.drop_table('grocery_list_icon')
    # ### end Alembic commands ###
