"""groceryListItem change

Revision ID: 86c12339e5bc
Revises: 
Create Date: 2024-04-05 20:19:48.032555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c12339e5bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list_item', sa.Column('target_container_idx', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grocery_list_item', 'container', ['target_container_idx'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grocery_list_item', type_='foreignkey')
    op.drop_column('grocery_list_item', 'target_container_idx')
    # ### end Alembic commands ###
