"""big changes

Revision ID: 8ef49414ffe0
Revises: 49968ab827ac
Create Date: 2024-04-07 22:39:36.759355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ef49414ffe0'
down_revision: Union[str, None] = '49968ab827ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('container_id', sa.String(length=100), nullable=False))
    op.alter_column('container', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('container', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'container', ['container_id'])
    op.alter_column('container_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('container_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('container_type', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('container_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('container_type', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('grocery_list', sa.Column('grocery_list_id', sa.String(length=100), nullable=False))
    op.alter_column('grocery_list', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'grocery_list', ['grocery_list_id'])
    op.alter_column('grocery_list_change_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_type', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_icon', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('grocery_list_icon', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_icon', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('grocery_list_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('household', sa.Column('household_id', sa.String(length=100), nullable=False))
    op.alter_column('household', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('household', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'household', ['household_id'])
    op.alter_column('household_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('household_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item_category', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('item_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item_category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item_icon', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('item_icon', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('item_icon', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('member', sa.Column('pfp_bg_color', sa.String(length=7), nullable=False))
    op.alter_column('member', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('member', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('member_pfp', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('member_pfp', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('member_pfp', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('store', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('store', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_defined_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_defined_category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_defined_item', 'cate_idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_defined_item', 'user_defined_cate_idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_defined_item', 'icon_idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_defined_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_defined_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_defined_item', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_defined_item', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_defined_item', 'icon_idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_defined_item', 'user_defined_cate_idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_defined_item', 'cate_idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_defined_category', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_defined_category', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('store', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('store', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('member_pfp', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('member_pfp', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('member_pfp', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('member', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('member', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('member', 'pfp_bg_color')
    op.alter_column('item_icon', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('item_icon', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('item_icon', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('item_category', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('item_category', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('item_category', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('item', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('item', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('household_config', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('household_config', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'household', type_='unique')
    op.alter_column('household', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('household', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('household', 'household_id')
    op.alter_column('grocery_list_item', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_item', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_icon', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_icon', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_icon', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('grocery_list_change_type', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_type', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_log', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list_change_log', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'grocery_list', type_='unique')
    op.alter_column('grocery_list', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('grocery_list', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('grocery_list', 'grocery_list_id')
    op.alter_column('container_type', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('container_type', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('container_type', 'image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('container_item', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('container_item', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'container', type_='unique')
    op.alter_column('container', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('container', 'created_at',
               existing_type=sa.BigInteger(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('container', 'container_id')
    # ### end Alembic commands ###
